### ISSUE TITLE
Does the newest version support  multi-GPU training?

### ISSUE THREAD

**Issue by cc-cherie** [mycrazycracy/tf-kaldi-speaker#8]
Hi , 
 Thanks for your great job.  Does the newest version support  multi-GPU training? I find the multi-gpu setup in the file of "run_train_nnet.sh".

**Comment by mycrazycracy** [comment]
Hi, thanks for your interest. Actually, I have made the multi-gpu support to this code. But due to some reasons, I cannot upload the code at this moment. 
I stop commit the change when I try to add this function since it is important for large datasets. So you can find some files that contain code about the gpu support...
Anyway, I will commit the multi-gpu support in the next 3 months when I finish my thesis.  I'm really sorry!

**Comment by mycrazycracy** [comment]
Hi, the multi-gpu code is released now :-)
