### ISSUE TITLE
About the GhostVLAD pooling

### ISSUE THREAD

**Issue by kjw11** [mycrazycracy/tf-kaldi-speaker#9]
Thanks for realsing this useful implement, it greatly helps my work. 
However, I notice that there are GhostVLAD pooling experiments in RESULTS.md file, but I did not find relevant function in pooling.py file. I currently need to do some tests on this popular pooling method.
Would you like to provide GhostVLAD pooling function? Truely appreciate your help.

**Comment by mycrazycracy** [comment]
Sorry! I just notice this issue... Actually, I released the VLAD code before. But since I found it is not helpful in my experiments, I deleted the related code. If you understand the formula of VLAD, it is very easy to implement. I may re-implement the pooling function in the future but it would certainly take some time. Sorry to reply late!

**Comment by kjw11** [comment]
Thanks for your reply. I will try it.
